malware_dir: "C:/Users/USER/Desktop/Malware"
benign_dir: "C:/Users/USER/Desktop/benign"
model_file: "malware_detection_model.joblib"
vectorizer_file: "feature_vectorizer.joblib"
test_size: 0.2
random_state: 42
n_estimators: 100
